- name: Configure AWS
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: us-east-1

- name: Update Kube Config
  run: eksctl utils write-kubeconfig --cluster voting-app-cluster --region us-east-1

- name: Apply Manifests
  run: kubectl apply -f k8s/
